# dear emacs, this is -*- python -*-
import waflib.Logs as msg

def configure(cnf):
    msg.info("configure [tests]...")

def build(bld):
    msg.info("build [tests]...")
    bld.program(
        features = 'cxx cxxprogram',
        source   = bld.path.ant_glob('*.cpp'),
        target   = 'termites_tests',
        includes = '../include .',
    )
