#! /usr/bin/env python
# Copyright (c) 2014 Foudil Brétel. All rights reserved.

def configure(cnf):
    cnf.env.TARGET_APP_TEST = 'unittestmain'
    cnf.env.TEST_INC_DIRS = ['../include', '.']


def build(bld):
    sources = [f for f in bld.env.SRC_SOURCES if not str(f)[-8:] == 'main.cpp']
    bld.program(
        name     = 'tests',
        features = 'cxx cxxprogram test',
        source   = bld.path.ant_glob('*.cpp') + sources,
        target   = bld.env.TARGET_APP_TEST,
        includes = bld.env.TEST_INC_DIRS,
    )

    from waflib.Tools import waf_unit_test
    bld.add_post_fun(waf_unit_test.summary)

    if bld.options.coverage:
        bld(name   = 'cov_run',
            rule   = '${SRC}',
            source = bld.env.TARGET_APP_TEST,
            always = True,
        )
        bld(name  = 'cov_lcov',
            rule  = (bld.env.LCOV +
                     ' --directory . --capture' +
                     ' --output-file ${env.LCOV_DIR}/run.info'),
            always = True,
            after = 'cov_run',
        )
        bld(name  = 'cov_genhtml',
            rule  = (bld.env.GENHTML +
                     ' --output-directory ${env.LCOV_DIR}' +
                     ' ${env.LCOV_DIR}/run.info'),
            always = True,
            after = 'cov_lcov',
        )
