#! /usr/bin/env python
# Copyright (c) 2014 Foudil Brétel. All rights reserved.

bld.program(
    features = 'cxx cxxprogram test',
    source   = bld.path.ant_glob('*.cpp'),
    target   = 'termites_tests',
    includes = '../include .',
)
