#!/usr/bin/env python
# Copyright (c) 2014 Foudil Brétel. All rights reserved.
# encoding: utf-8

def options(opt):
    bld = opt.get_option_group('build and install options')
    bld.add_option('--doxygen', action='store_true', default=False, help='Enable build of doxygen documentation')


def configure(cnf):
    if cnf.options.doxygen:
        cnf.find_program('doxygen', var='DOXYGEN', mandatory=True)

def build(bld):
    if bld.options.doxygen:
        bld(name = 'doxygen',
            rule   = ('${env.DOXYGEN} ${SRC[0].abspath()}'),
            source = 'doxygen.conf',
            always = True,
            # install_path = '${PREFIX}/share/${env.APPNAME}',
        )
